#webapp-creds.yaml

apiVersion: v1
kind: Secret
metadata:
  name: webapp-creds
type: Opaque
data:
  # القيم لازم تكون base64-encoded
  # مثال: echo -n "appuser" | base64 → Um9vdFBAc3MyMDI1

  DB_SERVERNAME: bXlzcWw=
  DB_USERNAME : YXBwdXNlcg==
  DB_PASSWORD : QXBwVSRlclBAc3MhMjAyNQ==
  DB_DBNAME:  YXp6YWRiX25ldw==



