version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"   # Jenkins web UI
      - "50000:50000" # For Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
    restart: unless-stopped

volumes:
  jenkins_home:

